### ISSUE TITLE
[Question] Vide and Trace

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#10215]
Hi guys! I am starting with Playwright 1.16.3 , and I am trying to use the Video Recording and Trace features, however, for some reason, I cant make them work. I could not find any video saved after the execution and the Trace just shows a blank page.
This is the playwright.config.ts I am using on my project:

`import { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
  use: {
    video: 'on',
    trace: 'on'
  },
  reporter: [ ['html', { outputFolder: 'test-results', outputFile: 'results.html' }]  ],
  timeout: 120000
};
export default config;`

I am running `npx playwright show-report test-results`
after executing only 1 test, it passed, it opens the report. I could see there is a trace at the end of the report, but it appears to be blank when opening. In terms of the video, no file has been generated.
 
I could see on the project the test-results folder with a trace.zip inside.

Is there something I am missing or doing wrong in there ?

The test only launches the browser and navigate and login to a page.

Thanks a lot

**Comment by aslushnikov** [comment]
@imartinflores as of today, you have to have a separate folder for HTML report - anything but `test-results/` would do. Try

```js
import { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
  use: {
    video: 'on',
    trace: 'on'
  },
  reporter: [ ['html', { outputFolder: 'html-report', outputFile: 'results.html' }]  ],
  timeout: 120000
};
export default config;
```

**Comment by imartinflores** [comment]
Hi @aslushnikov , thanks, really appreciate. That is exactly what I got, and I cant still make it work. I am gonna try downgrading playwright to 1.16.2 , because if I am not wrong (I made lot of commits Todays) it was working fine before, and I think I've upgraded when it stopped working. The folder is being generated, however the .html report file is not in there, neither the video and the trace still showing as blank.
Ill keep you updated when downgrading .

![image](https://user-images.githubusercontent.com/17011557/141212807-319a2f61-f2a0-4d70-aef2-4d4deaec191c.png)


Thanks!
Nacho

**Comment by imartinflores** [comment]
@aslushnikov did a quick try, installed @playwright/test 1.16.2 , the trace seems to be working now. The video file is not being generated yet and nor the .html report. However, now, when executing the show-report , its showing it (as before) and the trace works.

**Comment by dgozman** [comment]
@imartinflores Could you share a full repro please? I am not able to reproduce this with 1.16.2 or 1.16.3.

Also note that html reporter does not support `outputFile` parameter as written in your config. It only supports `outputFolder`.
```js
   reporter: [ ['html', { outputFolder: 'test-results', outputFile: 'results.html' }]  ]
```

**Comment by imartinflores** [comment]
Hi @dgozman  , thanks. I have removed the outputFile . I am trying it, but I am receiving another error now saying "describe()" can only be called in a test file. Which is weird.  What else can I send in order to make it easier for you to check it ? any recording or some stacktrace ?

**Comment by dgozman** [comment]
> What else can I send in order to make it easier for you to check it ?

Ideally, it would be a config file plus a single test file. If you have it somewhere on github that works too.

> I am trying it, but I am receiving another error now saying "describe()" can only be called in a test file.

Make sure you only have a single `@playwright/test` in your package.json, and both `import/require` and `npx playwright test` are run from the same place. Are you using monorepro with multiple `node_modules` folders?

**Comment by imartinflores** [comment]
@dgozman nvm - double check and there was a misspelling issue on the folder, I fixed and they are running.

This is the config file:
`
import { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
  use: {
    headless: false,
    video: 'on',
    trace: 'on'
  },
  reporter: [ ['html', { outputFolder: 'test-results' }] ,['junit', { outputFolder: 'test-results', outputFile: 'GdprReview.xml' }],
  ['list'] ],
  timeout: 120000
};
export default config;
`
The test file is just a test.describe() with a browser launch and a test() on it which is login in into an app. The report is being generated, I can see it opening after the test run. But this is what is happening with the Trace: 

![playwright](https://user-images.githubusercontent.com/17011557/142322017-ac895619-d4d4-4929-9c12-80a6c3ff914a.gif)

And there is no video file generated anywhere... This is all that get generated in the test-results folder after the test passed:
![image](https://user-images.githubusercontent.com/17011557/142323490-0e16befe-4477-42f6-a567-4e21c7a14cea.png)

let me know if its ok with that or if the test file is needed anyways please.

Thanks a lot!

**Comment by dgozman** [comment]
@imartinflores In the config you've shared I still see `['html', { outputFolder: 'test-results' }]`. Using `test-results` is not supported, please put any other directory there (or just omit it to use default playwright-report). This way you'll get both videos and traces.

**Comment by imartinflores** [comment]
Hi @dgozman , sorry, I understood in your previous comment "It only supports outputFolder." Ok, I removed it and I can see the trace working now, but still cannot see the video. I will keep trying it.

Thanks!

**Comment by imartinflores** [comment]
@dgozman So, If I just use the recordVideo option in the context as:
browser.newContext({recordVideo: {dir: 'videos/'}}) it works. But its not working when I use it through the config file for some reason for me. I will try to debug and see if I can find something else.
Thanks a lot for helping.

**Comment by dgozman** [comment]
@imartinflores Do you call `browser.newContext()` or `browser.newPage()` in your tests? There is a known limitation right now that `video` config option only works with built-in `page` and `context` objects that are provided for each test.

**Comment by imartinflores** [comment]
@dgozman  oh alright, may be that, so when launching the browser I was calling both, a browser.newContext() and a context.newPage() when opening a new tab (Im trying now a wrapper for dynamics). Setting the options on that context() I am calling is working fine.

**Comment by Sbrjt** [comment]
> There is a known limitation right now that video config option only works with built-in page and context objects that are provided for each test.

Love wasting hours on limitations like this.
