### ISSUE TITLE
[BUG] expect.toHaveScreenshot() generates an argument error

### ISSUE THREAD

**Issue by np-xavier** [microsoft/playwright#14186]
**Context:**
- Playwright Version: 1.22
- Operating System: Mac
- Node.js version: 17.3.1
- Browser: All

**Issue**

Since upgrading to 1.22, I implemented expect.toHaveScreenshot() like so, following the [documentation on Visual comparisons](https://playwright.dev/docs/test-snapshots):

`await expect(page).toHaveScreenshot('dashboard.png');`

VSCode indicates there's an issue (although it runs fine):

`Type '"dashboard.png"' has no properties in common with type '{ animations?: "disabled" | "allow"; caret?: "hide" | "initial"; clip?: { x: number; y: number; width: number; height: number; }; fullPage?: boolean; mask?: Locator[]; maxDiffPixelRatio?: number; ... 4 more ...; timeout?: number; }'.ts(2559)`

Which make sense because the [API docs say this method accepts an object](https://playwright.dev/docs/test-assertions#page-assertions-to-have-screenshot) rather than a string. I was just wondering how best to resolve this to make the error go away - and what should be the correct invocation as the original Visual comparisons docs don't seem to be aligned with the implementation?

**Comment by mxschmitt** [comment]
This should get fixed by https://github.com/microsoft/playwright/pull/14174. Thanks for reporting!

**Comment by mxschmitt** [comment]
This got shipped in 1.22.1

**Comment by svitlanaduman** [comment]
Hi , I'm using playwright 1.25 and cucumber, do I need something in the playwright config so the issue disappears, I'm still facing it.
Thanks
Svetlana
