### ISSUE TITLE
[BUG] Docker html report not working as expected since 1.22

### ISSUE THREAD

**Issue by JackSpa89** [microsoft/playwright#16667]
**Context:**
- Playwright Version: 1.22
- Operating System: Mac
- Node.js version: v16.13.2
- Browser: All

Hi.
I'm having issues with the playwright html reporter used inside a docker container and I think there was some regression error introduced between playwright version 1.21.1 and 1.22.0, because in 1.21.1 I was able to run the docker container with

**Code Snippet**

```bash
docker run -v $PWD:/playwright -w /playwright -it --rm -p 9323:9323 mcr.microsoft.com/playwright:v1.22.0-focal /bin/bash
```

and it would open the html report without problems. But since 1.22.0 it gives following message
```bash
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://127.0.0.1:9323' ]
}
````

Was there some change since 1.21.1 and 1.22 that would have caused this? Any help would be highly appreciated, as the docker setup is really quite helpful for me. 

Thanks and BR

**Comment by aslushnikov** [comment]
@JackSpa89 this should be fixed in recent releases. Could you please try running Playwright 1.25?

**Comment by JackSpa89** [comment]
Hi @aslushnikov .

Sadly it is not fixed. I tried with 1.25 and it still won't work, although it gives me this error message now 
´´´bash
  Serving HTML report at http://127.0.0.1:9323. Press Ctrl+C to quit.
Failed to open browser on http://127.0.0.1:9323
´´´

**Comment by aslushnikov** [comment]
> Sadly it is not fixed. I tried with 1.25 and it still won't work, although it gives me this error message now

@JackSpa89 what exactly do you mean by "not working"? is it hanging?

**Comment by JackSpa89** [comment]
@aslushnikov It simply wont open the browser, also navigating to http://127.0.0.1:9323 won't help.
Also rerunning 
```bash
npx playwright show-report
```
gives the same error message. 

If I install 1.21.1 again and run
```bash
npx playwright show-report
```
again, everything works fine again, my browser opens up automatically and I can see the report.

**Comment by aslushnikov** [comment]
@JackSpa89 ah indeed, I see. The issue is that we used to bind report serving to `0.0.0.0`, but changed that to `localhost` explicitly.

Let me discuss this with the folks on the meeting.

**Comment by aslushnikov** [comment]
For the record: we decided to expose host and port in html reporter config so that it can be configured to use `0.0.0.0`

**Comment by JoSchrader** [comment]
Using v1.27.0-beta-1665014412000 made the serving of the html report out of docker possible but i got a few questions.

Was the change of default port from 9323 to 9223 intentional?

I noticed 'host' and 'port' did not get suggested by my IDE while 'open' did. Do they need to be added in [utils/generate_types/overrides-test.d.ts](https://github.com/microsoft/playwright/blob/release-1.27/utils/generate_types/overrides-test.d.ts#L27)?

Can host and port be set when using 'show-report'? For me its defaults to 'http://localhost:9223', ignoring the settings in playwright.config.ts

**Comment by queicherius** [comment]
> Can host and port be set when using 'show-report'? For me its defaults to 'http://localhost:9223/', ignoring the settings in playwright.config.ts

This is also something I'd be interested in. I'm working on a remote machine, so I have to bind to `0.0.0.0` (or manually forward to localhost) to access the report.

**Comment by aslushnikov** [comment]
> Was the change of default port from 9323 to 9223 intentional?

@JoSchrader Oops it wasn't! Let me bring it back. Thank you for noticing. 

> Can host and port be set when using 'show-report'? For me its defaults to 'http://localhost:9223/', ignoring the settings in playwright.config.ts

@JoSchrader @queicherius Should be addressed by: https://github.com/microsoft/playwright/pull/18517
