### ISSUE TITLE
[BUG] No tests found using the test explorer - pw/test@1.26.0

### ISSUE THREAD

**Issue by RThuys** [microsoft/playwright#17500]
**Context:**
- Playwright Version: 1.26.0@latest
- Operating System: Windows
- Node.js version: 14.17.3
- Visual Studio Code version: 1.71.0
- Playwright for VSCode extension version: 0.2.10
- Browser: all
- Extra: 

**Repo**
Any new project I've tried

**Describe the bug**

Test runner doesn't finds tests when using  "@playwright/test": "^1.26.0" with Playwright for VSCode extension version: [0.2.10]

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/20083678/191490116-6e7948b4-34bd-4b91-911b-f9c12881abfb.png">

When using "@playwright/test": "^1.25.2" with Playwright for VSCode extension version: [0.2.10], the test explorer shows the correct amount of tests and works as normal

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/20083678/191476260-78af38bf-1219-4fc1-ae9e-41ac38a9193c.png">

This problem only occurs on my windows instance and doesn't occur on mac.
Manually the tests are executable and there is no problem: `npx playwright test`

**Comment by pavelfeldman** [comment]
Could you reload VS Code? We can't repro it.

**Comment by RThuys** [comment]
I've reloaded VS Code and also tried to disable the plugin, restarted VS Code, enable it again.

**Comment by idispatch75** [comment]
I have the exact same behaviour with node 16.15.1 (tested on Windows 10 only).

**Comment by AndreaPontrandolfo** [comment]
Same for me. I Just upgraded to 1.26 and now the extension is broken.
OS: Windows
Node: v16.10.0
Playwright version: 1.26.0
Playwright/test version: 1.26.0

**Comment by thedavidhoffman** [comment]
Any ETA on an updated Playwright for VSCode extension with this fix?

**Comment by qasimmahmood95** [comment]
Same for me. I updated on my Windows machine and it broke the VS Code extension. Just tried on my Mac and the extension works fine even after updating

**Comment by LoreCrux** [comment]
Not sure if this issue is effecting running tests in command line, but it may worth a look.

[https://github.com/microsoft/playwright/issues/17572](url)

**Comment by aslushnikov** [comment]
This is fixed; the fix will go public with 1.26.1 in a few minutes.

**Comment by peterbartha** [comment]
Still not working if the config is not directly in the root folder (with previous versions, it works as expected).
Sample folder structure:
```
monorepo/
├─ node_modules/
├─ packages/
│  ├─ app1/
│  │  ├─ tests/
│  │  ├─ src/
│  │  ├─ package.json <----- playwright/test@1.26.1 is added here
│  │  ├─ package-lock.json
│  │  ├─ playwright.config.json
├─ package.json
├─ package-lock.json
```

OS: MacOS 12.6 (ARM)
Node: v17.4.0
Playwright version: 1.26.1
`playwright/test` version: 1.26.1
`ms-playwright.playwright` VSCode plugin version: v0.2.10
VSCode version: 1.71.2

**Comment by mxschmitt** [comment]
> Still not working if the config is not directly in the root folder (with previous versions, it works as expected).
> Sample folder structure:
> ```
> monorepo/
> ├─ node_modules/
> ├─ packages/
> │  ├─ app1/
> │  │  ├─ tests/
> │  │  ├─ src/
> │  │  ├─ package.json <----- playwright/test@1.26.1 is added here
> │  │  ├─ package-lock.json
> │  │  ├─ playwright.config.json
> ├─ package.json
> ├─ package-lock.json
> ```
> 
> OS: MacOS 12.6 (ARM)
> Node: v17.4.0
> Playwright version: 1.26.1
> `playwright/test` version: 1.26.1
> `ms-playwright.playwright` VSCode plugin version: v0.2.10
> VSCode version: 1.71.2
> 

That's a different bug, I recommend filing a separate issue.

**Comment by Amuthan07** [comment]
I created playwright test files on my local machine, the test scripts were working for me
However when I pushed the same to a repo when I created a branch and tried to run it, it's not working
throwing the following error

Error: Playwright Test did not expect test() to be called here.
Most common reasons include:
- You are calling test() in a configuration file.
- You are calling test() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependencies in your package.json depends on @playwright/test.

   at Playwright/tests/Amazon/login.spec.js:6

  4 |
  5 |
> 6 | test('If sign-in button is there', async ({page}) => {
    |     ^
  7 |     //check if the sign-in button is present
  8 |     await page.goto(urlToTest);
  9 |     await page.getByRole('link', { name: 'Sign in', exact: true }).click();

    at TestTypeImpl._currentSuite (/Users/amu/Downloads/amazon-playwright-automation/Playwright/node_modules/playwright/lib/common/testType.js:71:13)
    at TestTypeImpl._createTest (/Users/amu/Downloads/amazon-playwright-automation/Playwright/node_modules/playwright/lib/common/testType.js:80:24)
    at /Users/amu/Downloads/amazon-playwright-automation/Playwright/node_modules/playwright/lib/transform/transform.js:256:12
    at Object.<anonymous> (/Users/amu/Downloads/amazon-playwright-automation/Playwright/tests/Amazon/login.spec.js:6:5)
Error: No tests found.
Make sure that arguments are regular expressions matching test files.
You may need to escape symbols like "$" or "*" and quote the arguments.

**Comment by mxschmitt** [comment]
Please file a new issue if you encounter an issue like that, thanks!
