### ISSUE TITLE
[BUG] connectOverCDP giving ECONNREFUSED despite chrome://inspect working

### ISSUE THREAD

**Issue by mark-wiemer** [microsoft/playwright#21022]
**Context:**

- Playwright 1.30.0
- Chrome 110.0.5481.104 (Official Build)
- Node 18.14.1
- Windows 11

From `npx envinfo --preset playwright --markdown`:

<details><summary>Additional context</summary>

## System:
 - OS: Windows 10 10.0.22621
 - Memory: 7.25 GB / 15.95 GB
## Binaries:
 - Node: 18.14.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 9.4.0 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE
## npmPackages:
 - playwright: ^1.30.0 => 1.30.0

</details>

**Repro steps**

1. Create a `TestUser` folder in the below path
1. Use Win+R to run `chrome --remote-debugging-port=9222 --user-data-dir="C:\Users\__user_folder__\AppData\Local\Google\Chrome\User Data\Default\TestUser"` (replacing `__user_folder__` as needed)
2. Use Node to run the below JS with Playwright 1.30.0:

    ```javascript
    var import_playwright = require("playwright");
    (async () => {
      await import_playwright.chromium.connectOverCDP("http://localhost:9222");
    })();
    ```

Expected: No exceptions thrown

Actual: Exception thrown with below details

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

browserType.connectOverCDP: connect ECONNREFUSED ::1:9222
=========================== logs ===========================
<ws preparing> retrieving websocket url from http://localhost:9222
============================================================
    at ...
    at Object.<anonymous> (...) {
  name: 'Error'
}
```

**Describe the bug**

`chrome://version` on the Chrome browser does show it was opened with the provided  args from Win+R.

Note that opening Edge and navigating to `chrome://inspect` (per [Debugging a Chrome instance with "remote-debugging-port" flag - StackOverflow](https://stackoverflow.com/a/69368719)) does show the opened Chrome window (IP redacted via editing local HTML):

![image](https://user-images.githubusercontent.com/7833360/220015585-3ca95ea1-1b5b-4b21-8529-a82c21d6e1ee.png)

**Comment by mark-wiemer** [comment]
Closed, it's working now with updated repro steps as the SO answer mentions:

> The issue is user-data-dir=.

> You can point to your current profile directory, it may cause some problems. Debugging don't start without this argument.

So, use Win+R to run `chrome --remote-debugging-port=9222 --user-data-dir="C:\Users\markw\AppData\Local\Google\Chrome\User Data\Default\TestUser"` or something similar and you should be all set to go.

Note I didn't do anything special to my `chrome` shortcut, it's the default from installation earlier today.

**Comment by mark-wiemer** [comment]
It was working a second ago, but not anymore. Trying to figure out what I changed to break things, reopening in the meantime.

**Comment by mxschmitt** [comment]
I think we already fixed it, could you try this version? https://playwright.dev/docs/canary-releases

And its this fix: https://github.com/microsoft/playwright/pull/20396

**Comment by mark-wiemer** [comment]
Yes, I'll check as soon as I have time. A bit busy today unfortunately, but thanks for the link!

**Comment by mark-wiemer** [comment]
Still failing with the `1.32.0-alpha-feb-23-2023` build, opened Chrome once and ran the JS snippet three times. Same exception as always.

Here are the package details from package-lock.json:

```
    "node_modules/@playwright/test": {
      "version": "1.32.0-alpha-feb-23-2023",
      "resolved": "https://registry.npmjs.org/@playwright/test/-/test-1.32.0-alpha-feb-23-2023.tgz",
      "integrity": "sha512-OyTLBy7+eEIOglGMlU/ImmL5Znka15R8yk3SdQroSH50bPmvTZafZc1kCxVKzi+EaU7bhifElFBOARrN4QFKfg==",
      "dev": true,
      "dependencies": {
        "@types/node": "*",
        "playwright-core": "1.32.0-alpha-feb-23-2023"
      },
      "bin": {
        "playwright": "cli.js"
      },
      "engines": {
        "node": ">=14"
      },
      "optionalDependencies": {
        "fsevents": "2.3.2"
      }
    },
    "node_modules/@playwright/test/node_modules/playwright-core": {
      "version": "1.32.0-alpha-feb-23-2023",
      "resolved": "https://registry.npmjs.org/playwright-core/-/playwright-core-1.32.0-alpha-feb-23-2023.tgz",
      "integrity": "sha512-V+XGMHcopgTAXroOaKwOOdw7YRs0p03T0GRAFmxK6i1nv5KKr7DxzB6AhG08OmxLWkDDcz6Diw9yCbqAWM4jGQ==",
      "dev": true,
      "bin": {
        "playwright": "cli.js"
      },
      "engines": {
        "node": ">=14"
      }
    },
```

**Comment by mark-wiemer** [comment]
I am getting the same with Edge 110.0.1587.50 (Official build) (64-bit)

**Comment by mxschmitt** [comment]
You only updated @playwright/test, either update playwright as well or change the import to:

```ts
var import_playwright = require("@playwright/test");
(async () => {
  await import_playwright.chromium.connectOverCDP("http://localhost:9222");
})();

```

**Comment by mark-wiemer** [comment]
Issue resolved with `npm install -D playwright@next` to install the `1.32.0-alpha-feb-23-2023` build of `playwright`. Thanks for your patience, glad this bug is fixed in a canary build :)
