### ISSUE TITLE
[BUG] TypeError: Cannot set property message of [object Object] which has only a getter

### ISSUE THREAD

**Issue by doichev-kostia** [microsoft/playwright#22688]
### System info
- Playwright Version: v1.33.0
- Operating System: macOS 13.2,
- Browser: All
- Other info:

An issue with custom Errors that have a getter for the message property.

For some reason, Playwright is trying to set the message property of the error object, which is not allowed in some Error classes.
So, this causes a TypeError to be thrown

### Source code

- [x] I provided the exact source code that allows reproducing the issue locally.

```ts
import { test } from "@playwright/test";
import { z } from "zod";

class MyError extends Error {
  #issues: string[] = [];
  constructor(message: string) {
    super();
    this.name = "MyError";
    this.#issues.push(message);
  }

  get message() {
    return this.#issues.join("\n");
  }
}

test("Error", async () => {
  // Error: Error message
  throw new Error("Error message");

  // TypeError: Cannot set property message of Error which has only a getter
  throw new MyError("Error message");

  z.object({
    name: z.string(),
  })
    // TypeError: Cannot set property message of [object Object] which has only a getter
    .parse({
      // throws ZodError with only message getter
      name: undefined,
    });
});

```

**Link to the GitHub repository with the repro**

[repo with an example](https://github.com/doichev-kostia/playwright-typeerror)

**Config file**

```ts
// playwright.config.ts
export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: "html",
  use: {
    trace: "on-first-retry",
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },

    {
      name: "firefox",
      use: { ...devices["Desktop Firefox"] },
    },

    {
      name: "webkit",
      use: { ...devices["Desktop Safari"] },
    },
  ],
});

```

**Steps**
- [Run the test]
- [Get an error]

**Expected**

The playwright should not modify the original error message as some custom Errors do not provide a setter

**Actual**

`TypeError: Cannot set property message of [object Object] which has only a getter`
`TypeError: Cannot set property message of Error which has only a getter`

**Comment by doichev-kostia** [comment]
A very dirty fix there could be 

```ts
import { ZodError } from "zod"

// @ts-expect-error - ZodError's message is readonly, but playwright expects it to be writable
ZodError.prototype.__defineSetter__('message', (value) => {
  console.log('Setting the message', value);
  return value;
});

```

**Comment by MatthewCaseres** [comment]
> ```ts
> // @ts-expect-error - ZodError's message is readonly, but playwright expects it to be writable
> ZodError.prototype.__defineSetter__('message', (value) => {
>   console.log('Setting the message', value);
>   return value;
> });
> ```

Adding this to `playwright.config.ts` did fix my error, thanks!

**Comment by aslushnikov** [comment]
@doichev-kostia this is fixed in @playwright/test@canary (upcoming 1.35)

**Comment by srsudar** [comment]
I'm on `"^1.36.1"` and am still seeing this error, although it's for a property in my own code on a property that is defined on a class like so:

```
  static plural = 'experimentActivities';
```

I'm compiling my typescript first using these instructions:

https://playwright.dev/docs/test-typescript#manually-compile-tests-with-typescript

The compilation succeeds without issue, but running playwright against the compiled files fails with the type error shown above.

This step in particular from the stack trace:

```
    at Module.f._compile (<snip>/node_modules/@playwright/test/lib/utilsBundleImpl.js:16:994)
```

Any thoughts on why that might be a problem, when the production code runs just fine?

**Comment by aslushnikov** [comment]
@srsudar could you please file a separate issue with a repro?

**Comment by srsudar** [comment]
I'll try and repro if it keeps happening. I managed to comment out the offending line and move on for now.
