### ISSUE TITLE
[BUG] Opening page with large number of IFrames crashes/hangs playwright

### ISSUE THREAD

**Issue by JannisBush** [microsoft/playwright#28086]
### System info
- Playwright Version: [v1.39]
- Operating System: [macOS 14, or all?]
- Browser: [All?]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

async testfile: `test_async.py`
```python
import asyncio

from playwright.async_api import async_playwright

async def main():
    async with async_playwright() as p:
        browser = await p.firefox.launch(headless=False) # Route does not work for Firefox?
        browser = await p.chromium.launch(headless=False)
        browser = await p.webkit.launch(headless=False)
        page = await browser.new_page()
        await page.route("**/abc", lambda route: route.fulfill(path="bug.html"))
        await page.goto("http://playwright.dev/abc")
        #await page.locator("#finished").wait_for(timeout=0.999*1000, state="attached")
        await browser.close()

asyncio.run(main())
```

sync testfile: `test_sync.py`
```
from playwright.sync_api import sync_playwright

def main():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        page = browser.new_page()
        page.route("**/abc", lambda route: route.fulfill(path="bug.html"))
        page.goto("http://playwright.dev/abc")
        #page.locator("#finished").wait_for(timeout=0.999, state="attached")
        browser.close()

main()
```

helper_file: `bug.html`
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

</body>


<script>
    window.onload = () => {
    for (let i=0; i<1000; i++) {
        let frame = document.createElement("iframe");
        frame.src = "https://playwright.dev";
        document.body.appendChild(frame);
        setTimeout(() => frame.remove(), 1000);
    }
}
</script>

</html>
```

**Steps**
- Run `python test_async.py`
- Run `python test_sync.py`
- Observe the error log + program does not terminate
- Optionally: change browser in the file

**Expected**

- Playwright should simply close the page/browser after the load event is fired on the page.

**Actual**

- Playwright does not terminate. 
- Async Error:
```
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<Connection.run() done, defined at /Users/sectec/Library/Caches/pypoetry/virtualenvs/hp-gq4YG2Vu-py3.11/lib/python3.11/site-packages/playwright/_impl/_connection.py:267> exception=AttributeError("'dict' object has no attribute '_object'")>
Traceback (most recent call last):
  File "/Users/sectec/Library/Caches/pypoetry/virtualenvs/hp-gq4YG2Vu-py3.11/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 276, in run
    await self._transport.run()
  File "/Users/sectec/Library/Caches/pypoetry/virtualenvs/hp-gq4YG2Vu-py3.11/lib/python3.11/site-packages/playwright/_impl/_transport.py", line 163, in run
    self.on_message(obj)
  File "/Users/sectec/Library/Caches/pypoetry/virtualenvs/hp-gq4YG2Vu-py3.11/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 235, in <lambda>
    self._transport.on_message = lambda msg: self.dispatch(msg)
                                             ^^^^^^^^^^^^^^^^^^
  File "/Users/sectec/Library/Caches/pypoetry/virtualenvs/hp-gq4YG2Vu-py3.11/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 393, in dispatch
    self._create_remote_object(
  File "/Users/sectec/Library/Caches/pypoetry/virtualenvs/hp-gq4YG2Vu-py3.11/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 443, in _create_remote_object
    result = self._object_factory(parent, type, guid, initializer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sectec/Library/Caches/pypoetry/virtualenvs/hp-gq4YG2Vu-py3.11/lib/python3.11/site-packages/playwright/_impl/_object_factory.py", line 67, in create_remote_object
    return Frame(parent, type, guid, initializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sectec/Library/Caches/pypoetry/virtualenvs/hp-gq4YG2Vu-py3.11/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 78, in __init__
    self._parent_frame = from_nullable_channel(initializer.get("parentFrame"))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sectec/Library/Caches/pypoetry/virtualenvs/hp-gq4YG2Vu-py3.11/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 513, in from_nullable_channel
    return channel._object if channel else None
           ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute '_object'
```
- Sync: program stalls, after `Ctrl+c`:
```
KeyboardInterrupt
Task was destroyed but it is pending!
task: <Task pending name='Task-7' coro=<Page.goto() done, defined at /Users/sectec/Library/Caches/pypoetry/virtualenvs/hp-gq4YG2Vu-py3.11/lib/python3.11/site-packages/playwright/_impl/_page.py:466> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[SyncBase._sync.<locals>.<lambda>() at /Users/sectec/Library/Caches/pypoetry/virtualenvs/hp-gq4YG2Vu-py3.11/lib/python3.11/site-packages/playwright/_impl/_sync_base.py:105, ProtocolCallback.__init__.<locals>.cb() at /Users/sectec/Library/Caches/pypoetry/virtualenvs/hp-gq4YG2Vu-py3.11/lib/python3.11/site-packages/playwright/_impl/_connection.py:193]>
```
- The error occurs only if there are at least 1000 IFrames on the page.
- Firefox does not reproduce but this is caused by the route not being applied there. Why is this the case?
- This bug was discovered while trying to reproduce the following bug: https://github.com/microsoft/playwright-python/issues/1268
    - That bug always occurs on an internal test page
    - The page has many Iframes that close themselves

**Comment by mxschmitt** [comment]
I can reproduce, the reason is that we cleanup the frames if there are too many on the page:

```
{"guid":"frame@3537325bfdae9c89b0f2842abb91298c","method":"__dispose__","params":{"reason":"gc"}}
```

**Comment by DetachHead** [comment]
i ran into this issue while automating sap webgui. since it creates about 10 iframes per page, navigating between pages for several minutes causes the crash

**Comment by bayramkzk** [comment]
I am getting the same exception while automating a task, is there a quick workaround to deal with it for now?

**Comment by dangotbanned** [comment]
@dgozman is this related to #28629?

**Comment by dgozman** [comment]
@dangotbanned Yes, this should be fixed in the next release with #28629.

**Comment by zhoutianrui-tongji** [comment]
I had a similar problem! When will it be perfected? I can't thank u more! : )

**Comment by aa-dank** [comment]
Using 1.40.0 and still getting this error from page.eval_on_selector_all and page.evaluate calls
