### ISSUE TITLE
[Bug]:  New version 1.42 breaks auth redirects in chromium

### ISSUE THREAD

**Issue by LindseyHobbs** [microsoft/playwright#29749]
### Version

1.42

### Steps to reproduce

We have an app that requires an OKTA login, and to handle the redirect we've defined this in our playwright.config.js file
use: {
        channel: 'chromium',
        extraHTTPHeaders: {
          Accept: 'application/vnd.github.v3+json, application/json, text/plain, */*',
        }
}

Once the app goes to sign in now after the creds have been entered it redirects to a page with an error message like this 

This site can’t be reached
might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_URL

If I switch to channel: 'chrome' or 'msedge-beta' it works just fine, it seems to be an issue specifically with chromium

### Expected behavior

I expect that after an authenticated login, the browser should correctly re-route

### Actual behavior

The page no longer re-routes correctly and re-routes to an erroneous url

### Environment

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.42 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - ~/.nvm/versions/node/v20.7.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.7.0/bin/npm
  Managers:
    Homebrew: 4.2.4 - /opt/homebrew/bin/brew
    Maven: 3.9.6 - /opt/homebrew/bin/mvn
    pip3: 23.3.1 - /opt/homebrew/bin/pip3
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 14.0.3 - /usr/bin/gcc
    Git: 2.39.2 - /usr/bin/git
    Clang: 14.0.3 - /usr/bin/clang
    Curl: 8.4.0 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  Virtualization:
    Docker: 25.0.3 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
  IDEs:
    IntelliJ: 2022.3.2
    VSCode: 1.87.0 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 17.0.9 - /Users/myUserName/.jenv/shims/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.11.7 - /opt/homebrew/bin/python3

  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 17.3.1
```

**Comment by pavelfeldman** [comment]
Please follow the issue template when filing bug reports. We need to be able to repro it to fix it.

**Comment by Exoow** [comment]
FYI @pavelfeldman : we experience the same (from Microsoft AAD towards our app).

**Comment by irinakartun** [comment]
faced the same issue when doing login with auth0 provider in chromium. 
I have my local app running on http://localhost:3000/ and when page is redirected on credentials page, an error thrown.
Note: it works fine when app host is DNS not localhost

**Comment by Exoow** [comment]
@LindseyHobbs I haven't tried it in code, but workaround seems to be refreshing the page, or navigating explicitly to localhost:port after the login.

**Comment by Pharb** [comment]
FYI @pavelfeldman this is cased by this bug: https://issues.chromium.org/issues/327022946
Affecting Chromium 123.0.6312.4 used by Playwright [v1.42.0](https://github.com/microsoft/playwright/releases/tag/v1.42.0) and Chrome v123 beta

**Comment by jaktestowac** [comment]
Same issue here:
![obraz](https://github.com/microsoft/playwright/assets/72373858/27cc9125-0185-4e13-be39-5b6717a6613b)
What can be done? 
1. After seeing this problem page reload can be solution, but sometimes timeout is needed:
```typescript
await page.waitForTimeout(2000);
await page.reload();
```
2. Another option is downgrading to previous Playwright version: `npm install @playwright/test@1.41` and installing old browsers `npx playwright install`

**Comment by ifeltsweet** [comment]
@pavelfeldman please reopen, we are experiencing the same issue when directing back from AWS Cognito OAuth flow.

**Comment by Exoow** [comment]
It's already fixed in Chromium, if you can skip this version and wait for the next version of Playwright it will likely be included. It's what I do. 😄

**Comment by Josef-Reichardt** [comment]
This problem is still there, right? There is a playwright 1.42.1 but this still contains chromium 123. Any hint when the chromium verision in playwright will be updated? Version 125 is already available.

**Comment by Pharb** [comment]
Fixed with [v1.43.0](https://github.com/microsoft/playwright/releases/tag/v1.43.0) which ships with Chromium 124.0.6367.29 ✅

**Comment by Horsty80** [comment]
> Fixed with [v1.43.0](https://github.com/microsoft/playwright/releases/tag/v1.43.0) which ships with Chromium 124.0.6367.29 ✅

That fixed the bug :) thanks ✌️
