### ISSUE TITLE
[REGRESSION]: Brand new install of playwright, unable to run chromium with show browser using vscode

### ISSUE THREAD

**Issue by Bloke-Bloke** [microsoft/playwright#30339]
### Version

1.41.0

### Steps to reproduce

1. Create a new folder in vscode
2. Open to that folder
3. Open Command + Shift + P and run 'install playwright'
4. Let all the defaults install
5. Click the testing tab in vscode and you'll see the tests or e2e folder playwright added
6. There will be 2 examples. We do not want to run the individual examples, but instead the parent folder of both of them so they both run at the same time
7. Before clicking run, make sure that 'show browser' is enabled
8. Click run

### Expected behavior

Tests to pass

### Actual behavior

Tests fail with 'frame has been detached'

### Additional context

Firefox is fine
This leads me to believe there is an issue in the latest chromium supported browser.. I was also getting some weird errors on my CICD pipeline and I have a suspicion that whatever is causing this is also causing that failure

### Environment

```shell
MAC OS/X
14.3

npm -v
10.3.0

node -v
v21.1.0
```

**Comment by mxschmitt** [comment]
I can reproduce:

```
  pw:browser [pid=44440][err] [44496:259:0411/164659.679651:FATAL:world_safe_v8_reference.cc(50)] Check failed: &world == &script_state->World() (0x12b001a0f18 vs. 0x12b001a0978) +924ms
  pw:browser [pid=44440][err] 0   Chromium Framework                  0x0000000126a67844 base::debug::CollectStackTrace(void const**, unsigned long) + 28 +0ms
  pw:browser [pid=44440][err] 1   Chromium Framework                  0x0000000126a5bff0 base::debug::StackTrace::StackTrace() + 24 +0ms
  pw:browser [pid=44440][err] 2   Chromium Framework                  0x00000001269c95d8 logging::LogMessage::Flush() + 132 +0ms
  pw:browser [pid=44440][err] 3   Chromium Framework                  0x00000001269c94d4 logging::LogMessage::~LogMessage() + 36 +0ms
  pw:browser [pid=44440][err] 4   Chromium Framework                  0x00000001269b5be8 logging::(anonymous namespace)::CheckLogMessage::~CheckLogMessage() + 124 +0ms
  pw:browser [pid=44440][err] 5   Chromium Framework                  0x00000001269b5c38 logging::(anonymous namespace)::CheckLogMessage::~CheckLogMessage() + 12 +0ms
  pw:browser [pid=44440][err] 6   Chromium Framework                  0x00000001269b598c logging::CheckError::~CheckError() + 44 +0ms
  pw:browser [pid=44440][err] 7   Chromium Framework                  0x00000001269b59d4 logging::CheckError::~CheckError() + 12 +0ms
  pw:browser [pid=44440][err] 8   Chromium Framework                  0x000000012965d804 blink::WorldSafeV8ReferenceInternal::MaybeCheckCreationContextWorld(blink::DOMWrapperWorld const&, v8::Local<v8::Value>) + 224 +0ms
  pw:browser [pid=44440][err] 9   Chromium Framework                  0x0000000129629568 blink::WorldSafeV8Reference<v8::Value>::WorldSafeV8Reference(v8::Isolate*, v8::Local<v8::Value>) + 156 +0ms
  pw:browser [pid=44440][err] 10  Chromium Framework                  0x000000012a131f70 blink::bindings::AsyncIterationSourceBase::RunFulfillStepsCallable::Call(blink::ScriptState*, blink::ScriptValue) + 120 +0ms
  pw:browser [pid=44440][err] 11  Chromium Framework                  0x000000012961e220 blink::ScriptFunction::Callable::CallRaw(blink::ScriptState*, v8::FunctionCallbackInfo<v8::Value> const&) + 124 +0ms
  pw:browser [pid=44440][err] 12  ???                                 0x0000000157e10530 0x0 + 5769332016 +0ms
  pw:browser [pid=44440][err] 13  ???                                 0x0000000157f1c938 0x0 + 5770430776 +0ms
  pw:browser [pid=44440][err] 14  ???                                 0x0000000157e3c188 0x0 + 5769511304 +0ms
  pw:browser [pid=44440][err] 15  ???                                 0x0000000157e0b598 0x0 + 5769311640 +0ms
  pw:browser [pid=44440][err] 16  Chromium Framework                  0x0000000123ab1414 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) + 2024 +0ms
  pw:browser [pid=44440][err] 17  Chromium Framework                  0x0000000123ab1d38 v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) + 88 +0ms
  pw:browser [pid=44440][err] 18  Chromium Framework                  0x0000000123ab1e84 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*) + 60 +0ms
  pw:browser [pid=44440][err] 19  Chromium Framework                  0x0000000123adb780 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) + 200 +0ms
  pw:browser [pid=44440][err] 20  Chromium Framework                  0x0000000123adbd0c v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) + 136 +1ms
  pw:browser [pid=44440][err] 21  Chromium Framework                  0x0000000125bfd32c blink::scheduler::EventLoop::PerformMicrotaskCheckpoint() + 156 +0ms
  pw:browser [pid=44440][err] 22  Chromium Framework                  0x0000000125c09af0 blink::scheduler::AgentGroupSchedulerImpl::PerformMicrotaskCheckpoint() + 452 +0ms
  pw:browser [pid=44440][err] 23  Chromium Framework                  0x0000000125c19db8 blink::scheduler::MainThreadSchedulerImpl::PerformMicrotaskCheckpoint() + 496 +0ms
  pw:browser [pid=44440][err] 24  Chromium Framework                  0x0000000125c1f514 blink::scheduler::MainThreadSchedulerImpl::OnTaskCompleted(base::WeakPtr<blink::scheduler::MainThreadTaskQueue>, base::sequence_manager::Task const&, base::sequence_manager::TaskQueue::TaskTiming*, base::LazyNow*) + 92 +0ms
  pw:browser [pid=44440][err] 25  Chromium Framework                  0x0000000125c259d8 blink::scheduler::MainThreadTaskQueue::OnTaskCompleted(base::sequence_manager::Task const&, base::sequence_manager::TaskQueue::TaskTiming*, base::LazyNow*) + 112 +0ms
  pw:browser [pid=44440][err] 26  Chromium Framework                  0x00000001234c81c8 base::RepeatingCallback<void (std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>> const&, media::CdmMessageType, std::__Cr::vector<unsigned char, std::__Cr::allocator<unsigned char>> const&)>::Run(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>> const&, media::CdmMessageType, std::__Cr::vector<unsigned char, std::__Cr::allocator<unsigned char>> const&) const & + 100 +0ms
  pw:browser [pid=44440][err] 27  Chromium Framework                  0x0000000126a155b8 base::sequence_manager::internal::SequenceManagerImpl::NotifyDidProcessTask(base::sequence_manager::internal::SequenceManagerImpl::ExecutingTask*, base::LazyNow*) + 136 +0ms
  pw:browser [pid=44440][err] 28  Chromium Framework                  0x0000000126a15ce0 non-virtual thunk to base::sequence_manager::internal::SequenceManagerImpl::DidRunTask(base::LazyNow&) + 136 +0ms
  pw:browser [pid=44440][err] 29  Chromium Framework                  0x0000000126a2683c base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) + 864 +0ms
  pw:browser [pid=44440][err] 30  Chromium Framework                  0x0000000126a26388 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() + 104 +0ms
  pw:browser [pid=44440][err] 31  Chromium Framework                  0x00000001269d01fc base::MessagePumpDefault::Run(base::MessagePump::Delegate*) + 120 +0ms
  pw:browser [pid=44440][err] 32  Chromium Framework                  0x0000000126a26f38 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) + 348 +0ms
  pw:browser [pid=44440][err] 33  Chromium Framework                  0x00000001269f5440 base::RunLoop::Run(base::Location const&) + 400 +0ms
  pw:browser [pid=44440][err] 34  Chromium Framework                  0x000000012c2d27cc content::RendererMain(content::MainFunctionParams) + 1368 +0ms
  pw:browser [pid=44440][err] 35  Chromium Framework                  0x0000000125f53600 content::RunOtherNamedProcessTypeMain(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>> const&, content::MainFunctionParams, content::ContentMainDelegate*) + 540 +0ms
  pw:browser [pid=44440][err] 36  Chromium Framework                  0x0000000125f541c8 content::ContentMainRunnerImpl::Run() + 692 +0ms
  pw:browser [pid=44440][err] 37  Chromium Framework                  0x0000000125f52938 content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) + 824 +0ms
  pw:browser [pid=44440][err] 38  Chromium Framework                  0x0000000125f52d3c content::ContentMain(content::ContentMainParams) + 112 +0ms
  pw:browser [pid=44440][err] 39  Chromium Framework                  0x00000001228053dc ChromeMain + 540 +0ms
  pw:browser [pid=44440][err] 40  Chromium Helper (Renderer)          0x0000000100880b0c main + 364 +0ms
  pw:browser [pid=44440][err] 41  dyld                                0x0000000186a8e0e0 start + 2360 +0ms
  pw:browser [pid=44440][err] Crash keys: +0ms
  pw:browser [pid=44440][err]   "discardable-memory-free" = "6668288" +0ms
  pw:browser [pid=44440][err]   "discardable-memory-allocated" = "8388608" +0ms
  pw:browser [pid=44440][err]   "view-count" = "1" +0ms
  pw:browser [pid=44440][err]   "loaded-origin-0" = "https://playwright.dev" +0ms
  pw:browser [pid=44440][err]   "web-frame-count" = "1" +0ms
  pw:browser [pid=44440][err]   "gpu-glver" = "OpenGL ES 2.0.0 (ANGLE 2.1.22780 git hash: f4ecbe6f136a)" +0ms
  pw:browser [pid=44440][err]   "gpu-generation-intel" = "0" +0ms
  pw:browser [pid=44440][err]   "gpu-vsver" = "1.00" +0ms
  pw:browser [pid=44440][err]   "gpu-psver" = "1.00" +0ms
  pw:browser [pid=44440][err]   "gpu-driver" = "14.4.1" +0ms
  pw:browser [pid=44440][err]   "gpu_count" = "1" +0ms
  pw:browser [pid=44440][err]   "gpu-devid" = "0x0000" +0ms
  pw:browser [pid=44440][err]   "gpu-venid" = "0x106b" +0ms
  pw:browser [pid=44440][err]   "renderer_foreground" = "true" +0ms
  pw:browser [pid=44440][err]   "v8_ro_space_firstpage_address" = "0x102e00000000" +0ms
  pw:browser [pid=44440][err]   "v8_isolate_address" = "0x13000e80000" +0ms
  pw:browser [pid=44440][err]   "variations" = "f38ef081-ca7d8d80,b357b792-3f4a17df,9481ce98-3d47f4f4,70678518-dee66fa8,be338734-dee66fa8,5f9907a9-dee66fa8,8eeccb9a-dee66fa8,2b465683-dee66fa8,52fc7926-dee66fa8,a41a7188-dee66fa8,ff71bfdc-dee66fa8,6daa4147-dee66fa8,4b935545-3d47f4f4,9a38bae3-3d47f4f4,2d1e43a3-3d47f4f4,386dc267-3d47f4f4,6b260bea-b31978bc,d69d967d-3695c92e," +0ms
  pw:browser [pid=44440][err]   "num-experiments" = "18" +0ms
  pw:browser [pid=44440][err]   "reentry_guard_tls_slot" = "266" +0ms
  pw:browser [pid=44440][err]   "switch-23" = "--variations-seed-version" +0ms
  pw:browser [pid=44440][err]   "switch-22" = "--field-trial-handle=1718379636,r,6316926978755035825,5847944190" +0ms
  pw:browser [pid=44440][err]   "switch-21" = "--shared-files" +0ms
  pw:browser [pid=44440][err]   "switch-20" = "--launch-time-ticks=14854744013" +0ms
  pw:browser [pid=44440][err]   "switch-19" = "--time-ticks-at-unix-epoch=-1712831964257339" +0ms
  pw:browser [pid=44440][err]   "switch-18" = "--renderer-client-id=6" +0ms
  pw:browser [pid=44440][err]   "switch-17" = "--enable-main-frame-before-activation" +0ms
  pw:browser [pid=44440][err]   "switch-16" = "--enable-gpu-memory-buffer-compositor-resources" +0ms
  pw:browser [pid=44440][err]   "switch-15" = "--enable-zero-copy" +0ms
  pw:browser [pid=44440][err]   "switch-14" = "--num-raster-threads=4" +0ms
  pw:browser [pid=44440][err]   "switch-13" = "--lang=en-GB" +0ms
  pw:browser [pid=44440][err]   "switch-12" = "--disable-databases" +0ms
  pw:browser [pid=44440][err]   "switch-11" = "--allow-pre-commit-input" +0ms
  pw:browser [pid=44440][err]   "switch-10" = "--remote-debugging-pipe" +0ms
  pw:browser [pid=44440][err]   "switch-9" = "--force-color-profile=srgb" +0ms
  pw:browser [pid=44440][err]   "switch-8" = "--file-url-path-alias=/gen=/Users/maxschmitt/Library/Caches/ms-p" +0ms
  pw:browser [pid=44440][err]   "switch-7" = "--enable-automation" +0ms
  pw:browser [pid=44440][err]   "switch-6" = "--disable-breakpad" +0ms
  pw:browser [pid=44440][err]   "switch-5" = "--disable-background-timer-throttling" +0ms
  pw:browser [pid=44440][err]   "switch-4" = "--disable-back-forward-cache" +0ms
  pw:browser [pid=44440][err]   "switch-3" = "--no-sandbox" +0ms
  pw:browser [pid=44440][err]   "switch-2" = "--enable-dinosaur-easter-egg-alt-images" +0ms
  pw:browser [pid=44440][err]   "switch-1" = "--user-data-dir=/var/folders/gs/d87p6_k17rz4ww4jr7kndrmr0000gn/T" +0ms
  pw:browser [pid=44440][err]   "num-switches" = "26" +0ms
  pw:browser [pid=44440][err]   "commandline-disabled-feature-13" = "Translate" +0ms
  pw:browser [pid=44440][err]   "commandline-disabled-feature-12" = "PaintHolding" +0ms
  pw:browser [pid=44440][err]   "commandline-disabled-feature-11" = "MediaRouter" +0ms
  pw:browser [pid=44440][err]   "commandline-disabled-feature-10" = "LazyFrameLoading" +0ms
  pw:browser [pid=44440][err]   "commandline-disabled-feature-9" = "ImprovedCookieControls" +0ms
  pw:browser [pid=44440][err]   "commandline-disabled-feature-8" = "HttpsUpgrades" +0ms
  pw:browser [pid=44440][err]   "commandline-disabled-feature-7" = "GlobalMediaControls" +0ms
  pw:browser [pid=44440][err]   "commandline-disabled-feature-6" = "DialMediaRouteProvider" +0ms
  pw:browser [pid=44440][err]   "commandline-disabled-feature-5" = "DestroyProfileOnBrowserClose" +0ms
  pw:browser [pid=44440][err]   "commandline-disabled-feature-4" = "CertificateTransparencyComponentUpdater" +0ms
  pw:browser [pid=44440][err]   "commandline-disabled-feature-3" = "AvoidUnnecessaryBeforeUnloadCheckSync" +0ms
  pw:browser [pid=44440][err]   "commandline-disabled-feature-2" = "AutoExpandDetailsElement" +0ms
  pw:browser [pid=44440][err]   "commandline-disabled-feature-1" = "AcceptCHFrame" +0ms
  pw:browser [pid=44440][err]   "commandline-enabled-feature-2" = "NetworkServiceInProcess" +0ms
  pw:browser [pid=44440][err]   "commandline-enabled-feature-1" = "NetworkService" +0ms
  pw:browser [pid=44440][err]   "osarch" = "arm64" +0ms
  pw:browser [pid=44440][err]   "pid" = "44496" +0ms
  pw:browser [pid=44440][err]   "ptype" = "renderer" +0ms
  pw:browser [pid=44440][err]  +0ms
```

Repro:

```ts
test('repro', async ({ reusedContext }) => {
  let context = await reusedContext();
  let page = await context.newPage();
  await page.goto('https://playwright.dev/');
  context = await reusedContext();
  page = await context.newPage();
  await page.goto('https://playwright.dev/');
});
```

**Comment by mxschmitt** [comment]
This should be fixed in v1.43.1.

**Comment by MicahRCM** [comment]
This is still broken in v1.43.1 if you run a group of tests with Show browser in chromium. Tests will keep failing with "frame has been detached" and give the "Aw, Snap!" Error 5.
