### ISSUE TITLE
[Bug] Chrome crashes when clicking on profile icon (top right)

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#30955]
Upstream bug: https://issues.chromium.org/issues/333967644

**Comment by mxschmitt** [comment]
This is fixed upstream / after 128.0.6585.0.

**Comment by Aboude-Adra** [comment]
@mxschmitt I'm still experiencing this issue with Playwright 1.48.1 and chrome 130.0.6723.70, I click on the three dots in top right corner to show options menu and chrome crashes, it doesn't happen with chromium or with chrome when opened normally and not via playwright.

Could this be the same issue or a different one?

**Comment by Aboude-Adra** [comment]
This is still happening as of Playwright v1.50.1 and Chrome Version 134.0.6998.118. 

I've also found that this **doesn't happen** when launching through `launchPersistentContext`

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
