### ISSUE TITLE
[Error]: Directory import is not supported resolving ES modules imported from..

### ISSUE THREAD

**Issue by zmirnes** [microsoft/playwright#32205]
### Version

1.46.1

### Steps to reproduce

Run npx playwright test when use imports like: "import Stack from '@mui/material/Stack'"

### Expected behavior

To run test without error and to resolve import normally

### Actual behavior

When I run npx playwright test I get this error: **Directory import 'C:\Users\mirnesz\Desktop\Projekti\frontend-dev\node_modules\@mui\material\Stack' is not supported resolving ES modules imported from C:\Users\mirnesz\Desktop\Projekti\frontend-dev\src\components\custom-datagrid\enhanced-datagrid-container.tsx**

### Environment

```shell
"@playwright/test": "^1.42.1",
"playwright": "^1.46.1",
```

**Comment by mxschmitt** [comment]
Might be already fixed by https://github.com/microsoft/playwright/issues/31811 - please re-try in canary: https://playwright.dev/docs/canary-releases

**Comment by mxschmitt** [comment]
Closing as per above. Feel free to re-file if Canary doesn't work for you.

**Comment by Luk-z** [comment]
@mxschmitt tested on  v1.47.0-alpha-2024-08-29 and still not working

**Comment by emielvanseveren** [comment]
Same issue for me

**Comment by mxschmitt** [comment]
@Luk-z @emielvanseveren could you please file a new issue with a reproduction? Thanks

**Comment by Luk-z** [comment]
I'm going to duplicate this issue because it is not fixed
