### ISSUE TITLE
[Bug]:  Playwright VSC Extension (with Show Browser enabled) prevent recording traces even option in config is on

### ISSUE THREAD

**Issue by jaktestowac** [microsoft/playwright#33155]
### Version

1.48.1

### Steps to reproduce

VSCode (1.94.2) with extension Playwright Test for VSCode (v1.1.7)
Default clean Playwright installation: 
`npm init playwright@latest --yes -- --quiet --browser=chromium`
 
Set traces recording in playwright config:
```
  use: {
    trace: 'on',
  },
```
Set `Show Browser` in Testing -> PLAYWRIGHT -> SETTINGS

Run any test with Extension runner  (green arrow):
![Image](https://github.com/user-attachments/assets/c8893af0-4f69-4f25-bd58-8a175cf03639)

No traces recorded in folder `test-results`

Similar terminal command:
`npx playwright test  --headed --grep='has title'`
It run test in browser and record traces (respect config settings).

### Expected behavior

Traces recorded while `Show Browser` enabled

### Actual behavior

Traces not recorded, config settings not respected

### Additional context

Traces are very helpful to find additional context after running tests. Limiting it only to Trace Viewer while using plugin make some discoveries harder.

In example Visual Testing with Trace Viewer and Browser differ. I wish to have recorded traces - but still use the browser and extension to quickly run tests (without using terminal) 

### Environment

System:
Windows 11

VSCode (1.94.2) 
Playwright Test for VSCode (v1.1.7)

Browsers: Chromium (127.0.2651.74)

**Comment by jaktestowac** [comment]
@pavelfeldman @dgozman when https://github.com/microsoft/playwright-vscode wil be released? 
Issue is resolved but end users waiting for fix.

**Comment by lumomatone** [comment]
@dgozman I am bit confused about if this issue is fixed. I am currently using Playwright version 1.54.1 with VS Code 1.103.2 and Playwright Test for VS Code 1.1.15. I have the setting use: {
    trace: 'on',
  },
, but it still does not create any trace.

**Comment by dgozman** [comment]
@lumomatone This is still an issue. The fix was reverted in https://github.com/microsoft/playwright-vscode/pull/556 due to errors it had introduced.

**Comment by lumomatone** [comment]
@dgozman Thank you for the quick response. Maybe another solution would be to work with the option "Show trace viewer" instead of "Show browser", but we have to keep the browser open after the test finishes (right now it instantly closes and only the trace viewer remains opened). That way we would also have the trace automatically open, which would not be the case if we just use "Show browser" option. 
@jaktestowac What do you think about this?

**Comment by Oscaruzzo** [comment]
This fix would be very useful
