### ISSUE TITLE
[Regression]: Playwright v1.54.0 breaks allure-playwright

### ISSUE THREAD

**Issue by brk9394** [microsoft/playwright#36645]
### Last Good Version

1.53.2

### First Bad Version

1.54.0

### Steps to reproduce

Please see example files / config below
1. Add any allure method to a test
    - E.g. `await allure.suite('Allure Suite');`
1. Run the test
    - E.g `npx playwright test`

### Expected behavior

- No errors
- The allure-results json files should contain the allure meta data
  - E.g 
```
{
    "name": "suite",
    "value": "Allure Suite"
}
```

### Actual behavior

1. Console error message when any allure method is called:
`no test runtime is found. Please check test framework configuration`

1. The allure meta data is not included in the `allure-results` JSON files

### Additional context

tests/example.spec.ts
```
import { test } from '@playwright/test';
import * as allure from "allure-js-commons";

test('allure-playwright demo', async () => {
  await allure.suite('Allure Suite');
});
```
package.json
```
{
  "name": "allure-playwright-demo",
  "version": "1.0.0",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.54.0",
    "@types/node": "^24.0.13",
    "allure-playwright": "^3.3.0"
  }
}
```
playwright.config.ts
```
import { defineConfig, devices } from '@playwright/test';
export default defineConfig({
  testDir: './tests',
  projects: [{
    name: 'chromium',
    use: { ...devices['Desktop Chrome'] }
  }],
  reporter: [
    ['list'],
    ['allure-playwright', { resultsDir: 'allure-results' }],
  ],
});
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 11.99 GB / 31.73 GB
  Binaries:
    Node: 22.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.102.0 - C:\Users\<redacted>\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.54.0 => 1.54.0
```

**Comment by pavelfeldman** [comment]
This is due to #36282, Allure was using internal property that was a subject to change, please report this with Allure.

**Comment by brk9394** [comment]
Thanks @pavelfeldman !

**Comment by brk9394** [comment]
Issue is resolved in allure-playwright 3.3.1

**Comment by Moander2243** [comment]
I'm still getting this error when using playwright test runner with **allure-cucumberjs**, even though all dependencies are up to date:
`no test runtime is found. Please check test framework configuration`

  
```
"devDependencies": {
    "@cucumber/cucumber": "^12.2.0",
    "@playwright/test": "^1.55.0",
    "@types/node": "^22.13.8",
    "allure-playwright": "^3.4.1",
    "allure-cucumberjs": "^3.4.1",
    "allure-playwright": "^3.4.1",
  }
```

```
Then('sample cucumber step', async function () {
    await allure.tag('New UI');
    await allure.tags('Essentials', 'Authentication');
})
```
