### ISSUE TITLE
[BUG] Failed to launch chromium because executable doesn't exist

### ISSUE THREAD

**Issue by danawoodman** [microsoft/playwright#4033]
**Context:**
- Playwright Version: 1.4.2
- Operating System: Mac 10.15.6
- Node.js version: 14.0.0
- Browser: Any

```
npx envinfo --preset playwright
npx: installed 1 in 1.177s

  System:
    OS: macOS 10.15.6
    Memory: 35.86 GB / 64.00 GB
  Binaries:
    Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v14.0.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

I am attempting to install Playwright but cannot get past the following error when trying to run a basic test:

```
   Failed to launch chromium because executable doesn't exist at /Users/danawoodman/Library/Caches/ms-playwright/chromium-799411/chrome-mac/Chromium.app/Contents/MacOS/Chromium
    Try re-installing playwright with "npm install playwright"
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

      at Chromium._launchProcess (node_modules/playwright/lib/server/browserType.js:123:19)
      at async Chromium._innerLaunch (node_modules/playwright/lib/server/browserType.js:66:75)
      at async ProgressController.run (node_modules/playwright/lib/server/progress.js:74:28)
      at async Chromium.launch (node_modules/playwright/lib/server/browserType.js:54:25)
      at async BrowserServerLauncherImpl.launchServer (node_modules/playwright/lib/browserServerImpl.js:32:25)
      at async PlaywrightRunner.getTests (node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:56:56)
      at async PlaywrightRunner.runTests (node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:87:30)
      at async TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:321:13)
      at async runJest (node_modules/@jest/core/build/runJest.js:372:19)
```

The file `~/Library/Caches/ms-playwright/chromium-799411/chrome-mac/Chromium.app/Contents/MacOS/Chromium` does not exist but this folder does `~/Library/Caches/ms-playwright/chromium-799411/chrome-mac/Chromium.app/Contents/Frameworks/Chromium\ Framework.framework`. Not sure why it is looking in the wrong location?

I have ran `yarn add playwright` and the package appears to install successfully. I've also tried to manually run `node node_modules/playwright/install.js` which gives me:

```
Removing unused browser at /Users/danawoodman/Library/Caches/ms-playwright/chromium-799411
Downloading chromium v799411 - 118.1 Mb [====================] 100% 0.0s
```

I've also attempted to remove `node_modules`, `yarn.lock` and `~/Library/Caches/ms-playwright` to reset things to a clean state but nothing is working. I'm at a losss for what to do and Googling/searching issues doesn't get me anything useful.

I don't think there is anything particularly unique with my setup. 

Is there a way to better troubleshoot why I can't get Playwright to work?

**Comment by arjun27** [comment]
Thanks! We saw issues with Node 14.0.0 and the fix is to upgrade to 14.1.0. Relevant previous issue: https://github.com/microsoft/playwright/issues/1988

**Comment by danawoodman** [comment]
@arjun27 I can confirm moving to `v14.1.0` did indeed fix my tests, thanks! Would be cool if it wasn't required to upgrade my whole app's node version just to get playwright working, but shouldn't be a huge issue

**Comment by arjun27** [comment]
Thanks! I agree with you in principle. This issue was caused by a change in Nodejs: https://github.com/nodejs/node/issues/33050

**Comment by alexfilothodoros** [comment]
Hello.

I keep having the same issue with v14.8.0 on macOS.

**Comment by vprasanth** [comment]
> Thanks! I agree with you in principle. This issue was caused by a change in Nodejs: [nodejs/node#33050](https://github.com/nodejs/node/issues/33050)

Due to issues like this, would it make sense to rethink how tags are grouped/created for this image? For example, bumping to a major version of node should probably cause a major bump for the tag for this image... Thoughts?

**Comment by molvqingtai** [comment]
Same problem with node v15.5.0 on WSL

**Comment by rollin-cogers** [comment]
Also having this problem with ubuntu 20.04 WSL with node v14.15.4

**Comment by gkushang** [comment]
We are also facing the same issue. This is very flaky behavior in our CI (Jenkins) instances

**Comment by PhillipMwaniki** [comment]
I'm facing the same issue with node v15.5.1 on macbook pro with apple silicone.

**Comment by Rasd-Alharaka** [comment]
تدوال

**Comment by bradydowling** [comment]
We're facing the same issue in Jenkins running on AWS with Node v14.15.1

**Comment by bradydowling** [comment]
@arjunattam seems like this issue should be reopened. We're facing the same issue in Jenkins running on AWS with Node v14.15.1.

**Comment by karoukastro** [comment]
Same issue here:
Operating System: Mac 11.2
Node.js version: 14.15.5

**Comment by mxschmitt** [comment]
@karoukastro @bradydowling @Rasd-Alharaka @PhillipMwaniki

Which OS, OS version and browser are you using?

**Comment by karoukastro** [comment]
@mxschmitt 
MacOs Big Sur
Version: 11.2

Browser: Chrome

**Comment by PhillipMwaniki** [comment]
> @karoukastro @bradydowling @Rasd-Alharaka @PhillipMwaniki
> 
> Which OS, OS version and browser are you using?

Macos Big Sur 11.1 on m1 macbook pro. I solved the issue by reinstalling playwright.

**Comment by karoukastro** [comment]
I tried reinstall it, but it issue is still here :(

**Comment by karoukastro** [comment]
I tried reinstall it, but it issue is still here :(
Other test I did was in Windows and it works fine, but I'd like to use my Mac

**Comment by mxschmitt** [comment]
These are different issues here. 
The issue by @karoukastro with Python is that probably you didn't run `python -m playwright install` which installs the browsers, or did you run it?

**Comment by karoukastro** [comment]
@mxschmitt I didn't, but now I could see the issue:

carol@Carolinas-MBP parodify % python3 -m playwright install
Failed to process descriptor at /Users/carol/robot/parodify/node_modules/playwright
Removing unused browser at /Users/carol/Library/Caches/ms-playwright/chromium-844399
Removing unused browser at /Users/carol/Library/Caches/ms-playwright/firefox-1225
Removing unused browser at /Users/carol/Library/Caches/ms-playwright/webkit-1423
(node:3565) UnhandledPromiseRejectionWarning: Error: ERROR: Playwright does not support chromium on mac11.2
    at Object.assert (/snapshot/playwright-cli/node_modules/playwright/lib/utils/utils.js:58:15)
    at revisionURL (/snapshot/playwright-cli/node_modules/playwright/lib/install/browserFetcher.js:143:13)
    at Object.downloadBrowserWithProgressBar (/snapshot/playwright-cli/node_modules/playwright/lib/install/browserFetcher.js:168:17)
    at async validateCache (/snapshot/playwright-cli/node_modules/playwright/lib/install/installer.js:103:9)
    at async Object.installBrowsersWithProgressBar (/snapshot/playwright-cli/node_modules/playwright/lib/install/installer.js:60:5)
(node:3565) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3565) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by adwam12** [comment]
Same issue here with webkit instead of chromium. It works when running on my machine, but when packaged and tested on another machine, i get 

`Failed to launch webkit because executable doesn't exist at /Users/adamOsgood/Library/Caches/ms-playwright/webkit-1402/pw_run.sh
    Try re-installing playwright with "npm install playwright"`

**Comment by bradydowling** [comment]
> Try re-installing playwright with "npm install playwright"

Just noticed this line, not sure if this is related but our project is using `yarn`, I wonder if that's the case for others or if anyone using `npm` is getting this issue as well.

**Comment by adwam12** [comment]
> > Try re-installing playwright with "npm install playwright"
> 
> Just noticed this line, not sure if this is related but our project is using `yarn`, I wonder if that's the case for others or if anyone using `npm` is getting this issue as well.

My project is not using yarn. Npm install does fix the issue for me, but I need my application to work on a users machine, even if they don't have Node/npm installed. So this isn't a good solution for me. (I'm using playwright with Electron)

**Comment by tristanpemble** [comment]
I am getting this on macOS 11.2.1 with node 15.9.0 and npm 7.5.3 when trying to use https://github.com/ruimarinho/gsts through a global npm install

**Comment by bdowling-chwy** [comment]
@arjunattam any thoughts on reopening this issue or info we can provide that would confirm if it is or is not still an issue?

**Comment by bradydowling** [comment]
@arjunattam any thoughts on reopening this issue or info we can provide that would confirm if it is or is not still an issue?

**Comment by adwam12** [comment]
I fixed my issue by downloading the browser to the project's node modules and accessing it from there and specifying the location with process.env.PLAYWRIGHT_BROWSERS_PATH. I'm using playwright with electron so this might not work for everyone but it did for me. 

 [How to download to specific location](https://playwright.dev/docs/installation)

**Comment by pjcalvo** [comment]
I am getting this issue now while using the pw docker image. https://hub.docker.com/_/microsoft-playwright

**Comment by StenPetrov** [comment]
This is still happening with JS Azure Functions

**Comment by gkushang** [comment]
I just published the solution here - https://gkushang.medium.com/playwright-failed-to-launch-browsers-how-to-solve-8b01d03fe5b9

**Comment by YacheLee** [comment]
I am using node v.14.15.1, but this issue is still there.

I solved this by removing the node_modules and reinstall again.
`rm -rf node_modules`
`npm i`

**Comment by AlexSapoznikov** [comment]
Using node v14.17, still same issue and unable to resolve even by following @adwam12`s solution.

**Comment by StfBauer** [comment]
Same issue here too on windows. 14.0.0.

**Comment by mxschmitt** [comment]
When using Playwright Test, you need to install the browsers yourself. You can do that via "npx playwright install".

**Comment by StfBauer** [comment]
@mxschmitt yes but they don't install 😀 without error.

**Comment by mxschmitt** [comment]
@StfBauer please create a new issue with the error etc.

**Comment by BrunoQuaresma** [comment]
Does anyone know how to fix the issue?

**Comment by gkushang** [comment]
@BrunoQuaresma 

This is a know issue for a long but we resolved it in our CI.  

I wrote medium post on the approach we took - https://gkushang.medium.com/playwright-failed-to-launch-browsers-how-to-solve-8b01d03fe5b9

Refer to prev issue: 
https://github.com/microsoft/playwright/issues/5767#issuecomment-898813860

**Comment by BrunoQuaresma** [comment]
I was getting this error on my local machine and after some time trying to figure out a solution, I got this working by:
- Removing the cache folder on `/Users/username/Library/Caches/ms-playwright`
- And installing chromium again `npx playwright install chromium`

**Comment by ssurabhi10** [comment]
> @gkushang 
> 
> This is a know issue for a long but we resolved it in our CI.
> 
> I wrote medium post on the approach we took - https://gkushang.medium.com/playwright-failed-to-launch-browsers-how-to-solve-8b01d03fe5b9
> 
> Refer to prev issue:
> [#5767 (comment)](https://github.com/microsoft/playwright/issues/5767#issuecomment-898813860)
> 
> and the comment above: [#4033 (comment)](https://github.com/microsoft/playwright/issues/4033#issuecomment-855276404)

Hi @gkushang,

I'm working on playwright GitHub workflow but facing an issue, 
`browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium-901522/chrome-linux/chrome`

Could you please explain where and how to use `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` and `PLAYWRIGHT_BROWSERS_PATH` in the `yaml` file? I have added these variables in Github secrets but that couldn't work directly.

ref - https://gkushang.medium.com/playwright-failed-to-launch-browsers-how-to-solve-8b01d03fe5b9

Sharing my code snippet, please let me know where and how to use these env vars in `yaml` file.

```
name: ci
on: push
jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
```

**Comment by gkushang** [comment]
@ssurabhi10 

`PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` should be with/before `run: npm install` command so that it skips the browser downloads. `PLAYWRIGHT_BROWSERS_PATH` can be set any time before running the tests. 

You may want to try setting below at the `Install dependencies` step,

```
env: 
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  PLAYWRIGHT_BROWSERS_PATH: <your-path>
```

**Comment by edspencer** [comment]
I banged my head against the wall for far too long on this before realizing that it was because `npx playwright install` was installing a different version of chromium than `npx playwright test` was looking for. Depressingly enough, this all came down to me not checking package-lock.json into source control.

@ssurabhi10 I'd be willing to be that if you add something like an `ls -al /home/runner/.cache/ms-playwright/` somewhere in your steps, it would show you existence of a folder called `chromium-907428` instead of `chromium-901522`. This is exactly what was facing me. I fixed it by deleting all my node_modules locally, setting all of my playwright-related npm module versions to precisely "1.14.0" and installing once more, then committing the generated package-lock.json. This worked for me.

**Comment by gkushang** [comment]
@edspencer - yes, the Playwright browsers are version controlled, and you'll need to install PerVersion copy of the browsers, e.g. `yarn add playwright-chromium@1.11.1` for `playwright v@1.11.1` as I mentioned in this [blog](https://gkushang.medium.com/playwright-failed-to-launch-browsers-how-to-solve-8b01d03fe5b9). 

That's an extra step for us too :( , as we need to update our PW Browsers docker images whenever we upadate Playwright.

**Comment by edspencer** [comment]
@gkushang your blog post was super helpful - thanks for writing it :)

**Comment by ssurabhi10** [comment]
> @ssurabhi10
> 
> `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` should be with/before `run: npm install` command so that it skips the browser downloads. `PLAYWRIGHT_BROWSERS_PATH` can be set any time before running the tests.
> 
> You may want to try setting below at the `Install dependencies` step,
> 
> ```
> env: 
>   PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
>   PLAYWRIGHT_BROWSERS_PATH: <your-path>
> ```

Hi @gkushang ,

After adding browser path, facing this error 
`error: unknown command 'test'. See 'npx playwright --help'.`

seems like `playwright/test` not found 

`name: ci
on: push

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.1.0'

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=${{ secrets.PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD }} npm install

      - name: Install browser dependencies
        run: PLAYWRIGHT_BROWSERS_PATH=${{ secrets.PLAYWRIGHT_BROWSERS_PATH }}

      - name: Run tests
        run: npm test`

**Comment by caio-ribeiro-pereira** [comment]
for those who got stuck in this issue and uses Heroku, I solve this problem by creating this alias on package.json:

``` json
"scripts": {
    "heroku-postbuild": "npm run build",
    "heroku-cleanup": "npx playwright install" // this will run after build success, and will put back the browser binary into default path /node_modules
  },
```

**Comment by sjpierobon** [comment]
solution  

Download chromium and create folders and place chromium 👍 

==> (win32)  https://chromium.cypress.io/win/canary_asan/97.0.4666.1

dist\your_program\playwright\driver\package\.local-browsers\chromium-930007\chrome-win\chrome.exe

**Comment by mxschmitt** [comment]
`npx playwright install` will fix it. For any further issues please file a new issue.
