### ISSUE TITLE
[BUG] Unable to upload big file on firefox.

### ISSUE THREAD

**Issue by niyarlatotep** [microsoft/playwright#4704]
**Context:**
- Playwright Version: 1.6.2
- Operating System: Win 10
- Node.js version: 14
- Browser: Firefox

**Code Snippet**

```javascript
const {firefox} = require('playwright');
const path = require('path');

(async function() {
    const browser = await firefox.launch({headless: false});
    try {
        const page = await browser.newPage();
        await page.goto('https://pdf.io/compress/');
        await page.setInputFiles('#upload_button input', path.join(process.cwd(), 'big.pdf'));
    } finally {
        await browser.close();
    }
})();
```

**Describe the bug**

When I try to upload big pdf, for example this one:  http://research.nhm.org/pdfs/29985/29985-001.pdf I get an error in example unable to upload file. At the same time chrome uploads file well, also small files are uploaded well on firefox but big ones don't.

**Comment by aslushnikov** [comment]
(I edited your script to include missing requires)

I unfortunately cannot reproduce - worked fine for me on both Mac OS and Windows 10 Enterprise. Any more specifics that would help reproducing this?

**Comment by niyarlatotep** [comment]
@aslushnikov I'm sorry it seems that I missed some important details. Try to comment `await `browser.close()`` and see what happens in browser window at the end of uploading process it takes some time then website says that it unable to upload file. I don't know if it website problem or not, but on chrome browser it works fine.

**Comment by JoelEinbinder** [comment]
Still working on a fix, but I can repro this on ubuntu 20.04 with firefox. It doesn't happen when I manually click the input and select the file, so something is messed up with our `setInputFiles`.

I get this error in the console when it fails. Very strange.
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://s104.123apps.com/pdf/upload/flow/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by achingbrain** [comment]
I've hit the same problem with Firefox recently - large file uploads don't work at all.

Here's a repo case with no dep on any third party service, just an echo server: https://github.com/achingbrain/playwright-ff-uploads

**Comment by niyarlatotep** [comment]
@pavelfeldman, @JoelEinbinder are there any plans to fix it?

**Comment by aslushnikov** [comment]
@achingbrain thank you for the awesome repro. 

This happens due to the way our network instrumentation interacts with POST data in Juggler. Specifically, it looks like
[NetUtil.readInputStream call](https://ffsearch.azurewebsites.net/#path=%2Fhome%2Fjoe%2Fplaywright%2Fbrowser_patches%2Ffirefox%2Fcheckout%2Fjuggler%2FNetworkObserver.js&line=757) is both:
a) racy & partial
b) closing the stream, making the final rewind-back fail.

Note that this all only happens with Blob uploads as POST requests.

**Comment by aslushnikov** [comment]
This is fixed now; the fix will be available in the next release - Playwright v1.12

Or on May 14 PST time in the `@next` channel: `npm i playwright@next`

**Comment by Saif4** [comment]
The issue still exists as soon as I go above 500kb file size the `setInputFiles` stuck on waiting on Firefox, same code on other browsers works just fine.

`"playwright": "1.27.1",`
Any suggestions?

**Comment by aslushnikov** [comment]
@Saif4 please file separately with a repro!
