### ISSUE TITLE
[BUG] Playwright does not support chromium on mac11.2

### ISSUE THREAD

**Issue by karoukastro** [microsoft/playwright#5443]
**Context:**
- Playwright Version: 1.8.1
- Operating System: MacOS Big Sur 11.2.1 (20D74)
- Node.js version: 14.15.5
- Browser: All
- Extra: Using with Robot Framework

```sh
$ npx envinfo --preset playwright
npx: installed 1 in 1.229s

  System:
    OS: macOS 11.2.1
    Memory: 1.12 GB / 16.00 GB
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    npm: 6.14.11 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Describe the bug**

Error when trying to install Playwright in my machine:

```sh
$ python3 -m playwright install
(node:1716) UnhandledPromiseRejectionWarning: Error: ERROR: Playwright does not support chromium on mac11.2
    at Object.assert (/snapshot/playwright-cli/node_modules/playwright/lib/utils/utils.js:58:15)
    at revisionURL (/snapshot/playwright-cli/node_modules/playwright/lib/install/browserFetcher.js:143:13)
    at Object.downloadBrowserWithProgressBar (/snapshot/playwright-cli/node_modules/playwright/lib/install/browserFetcher.js:168:17)
    at async validateCache (/snapshot/playwright-cli/node_modules/playwright/lib/install/installer.js:103:9)
    at async Object.installBrowsersWithProgressBar (/snapshot/playwright-cli/node_modules/playwright/lib/install/installer.js:60:5)
(node:1716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment]
@karoukastro ah, I see. This is fixed in the latest alpha release that's not stable yet. You can install it with:

```
$ pip install playwright==1.8.0a1
```

See our [installation docs](https://playwright.dev/python/docs/intro/) for details.

**Comment by karoukastro** [comment]
@aslushnikov thanks but it didn't fix the issue  :(

```
carol@Carolinas-MBP parodify % pip install playwright==1.8.0a1
Requirement already satisfied: playwright==1.8.0a1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (1.8.0a1)
Requirement already satisfied: greenlet==1.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from playwright==1.8.0a1) (1.0.0)
Requirement already satisfied: pyee>=8.0.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from playwright==1.8.0a1) (8.1.0)
Requirement already satisfied: typing-extensions in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from playwright==1.8.0a1) (3.7.4.3)
carol@Carolinas-MBP parodify % robot -d ./logs login.robot
==============================================================================
Login :: Teste da pagina login
==============================================================================
[ WARN ] Open Browser is for quick experimentation and debugging only. Use New Page for production.
[ WARN ] Keyword 'Take Screenshot' could not be run on failure:
Error: Tried to take screenshot, but no page was open.
Login com sucesso                                                     | FAIL |
Error: browserType.launch: Failed to launch chromium because executable doesn't exist at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/node_modules/playwright/.local-browsers/chromium-844399/chrome-mac/Chromium.app/Contents/MacOS/Chromium
Try re-installing playwright with "npm install playwright"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
------------------------------------------------------------------------------
Login :: Teste da pagina login                                        | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /Users/carol/robot/parodify/logs/output.xml
Log:     /Users/carol/robot/parodify/logs/log.html
Report:  /Users/carol/robot/parodify/logs/report.html
```

npm install playwright didn't work as well

**Comment by huzhou124** [comment]
`pip3 install playwright==1.8.0a1 ` and `npm install playwright`,then it worked.
Playwright does not support chromium on mac11.2 ,which is sloved.
`python3 -m playwright codegen --target python -o new.py -b chromium `:
```
from playwright.sync_api import sync_playwright

def run(playwright):
    browser = playwright.chromium.launch(headless=False)
```

**Comment by karoukastro** [comment]
@huzhou124 I'm using playwright 1.8.0a1 and Robot Framework, I tried everything but nothing worked yet :(

**Comment by aslushnikov** [comment]
@karoukastro playwright-python v1.9.0 was released just now. Could you please try this one?

**Comment by karoukastro** [comment]
@aslushnikov It worked with playwright v1.9.0! Thank you very much!! BTW nice bird :D

**Comment by aslushnikov** [comment]
awesome! 

P.S. Thanks!

**Comment by kblok** [comment]
@aslushnikov I just got a `Playwright does not support webkit on mac11.2` doing `npm install playwright`

**Comment by JayKishoreDuvvuri** [comment]
I still get this error on playwright that chromium is not supported on MacOs 11.2.

**Comment by juli1** [comment]
I still get this error even after installing the latest playwright python package recommended in this issue (version 1.9.0)

**Comment by JayKishoreDuvvuri** [comment]
Is it on Mac or Windows? I guess it should be definitely  on MacOS !

**Comment by juli1** [comment]
Yes, on Mac.

**Comment by JayKishoreDuvvuri** [comment]
So we are all waiting for this big to get fixed on MacOS soon!

**Comment by mxschmitt** [comment]
Please file a new bug with all the details since this one was "probably" fixed or its a regression. Thanks!

**Comment by wobsoriano** [comment]
Big Sur 11.4 gives `Error: Lock file is already being held` when you do `yarn add playwright`

**Comment by Macrow** [comment]
In Big Sur 11.4
```
yarn add playwright // success
```
I get some errors:
 ( I had the same errors with ```playwright@next``` )
```
npx playwright install
Failed to install browsers
Error: Lock file is already being held
```
