### ISSUE TITLE
Webkit and Firefox issue - doesn't select correct option provided when typed

### ISSUE THREAD

**Issue by saurabhxkapoor** [microsoft/playwright#759]
Steps to reproduce:
1. We have a drop down list from a selection box which has few hundred option values.
2. We do the following in puppeteer chromium to select ( focus on the selector, start typing the desired value):

```
        await page.focus(selector);
        await page.type(selector, value);
```

This thing works fine in chromium but in webkit and firefox, it doesn't select the correct option. Webkit is slightly better that it selects the most closest corect option (example -if we need to select option as-Internal Report Suite DE, it will select option value as Internal Report Suite but firefox is selecting only the first option from the selection

**Comment by JoelEinbinder** [comment]
I believe this is working as intended.

```js
await page.setContent(`
  <select>
    <option>animal</option>
    <option>baby</option>
    <option>cab</option>
    <option>dog</option>
  </select>
`)
await page.type('select', 'cab');
console.log(await page.$eval('select', s => s.value));
```

If you run this multiple times, you will get different results. Let's look at whats actually happening.

1. 'c' is pressed. "cab" is selected. This is consistent everywhere.
2. 'a' is pressed. Now if 'a' is pressed quickly after 'c', "cab" will continue to be selected. But if there has been a long time since 'c' was pressed, 'a' will select 'animal'
3. 'b' is pressed. If there has been a long time since 'a' was pressed, 'baby' will be selected. Otherwise 'animal' or 'cab' will stay selected.

Different browsers run at different speeds, which is why you might see somewhat consistent results with a certain browser. But fundamentally the test has a race.

Instead you can use `page.select(selector, value)` for consistent selection.

**Comment by pavelfeldman** [comment]
I don't think this is a timing issue, but I do think that Firefox behaves differently here. Firefox will always treat typed letter as the first letter of the option. WebKit and Chromium will actually do what you expect.

If that does not work on WebKit for you, could you tell me which OS you are using?

**Comment by saurabhxkapoor** [comment]
@pavelfeldman  - i am using mOS to test it locally. Webkit wasn't able to select the exact option.

**Comment by pavelfeldman** [comment]
I experimented with various long labels containing characters and spaces. All three browsers have their own behavior when typing on the select field. They all will try to match the whole text typed, but their heuristics will differ. For example, WebKit will actually open the drop box upon `space`. So you are left with the approach recommended by @JoelEinbinder for reliable behavior. Would `page.select(selector, value)` work for you?

**Comment by saurabhxkapoor** [comment]
@pavelfeldman  - even `page.select(selector, value) ` is not working for me on firefox on my application.

**Comment by saurabhxkapoor** [comment]
@pavelfeldman  - it is resolved. Used `querySelector` to retrieve the value.
``` document.querySelector('select [value="xyz"]').selected =true;```

**Comment by melekkalyoncu** [comment]
Hi, I am trying to select an option and I am using the latest version of playwright. 

`page.select (selector, selectionValue)` still doesn't work. It selects an empty option (this is not even an option that exists on the web page). I understand that we can use javascript to select an option, but I wonder if it is not working properly because I did something wrong or because the playwright is not capable of doing this or `page.select()` created for a different purpose than I thought?
