### ISSUE TITLE
[BUG] Allure-Report -> Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#8611]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows
- Node.js version: v12.14.1
- Browser: Chromium
- NPM version: 6.13.4

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

**Test script:** 
```javascript
import test from "@playwright/test";
import BasePage from "../../common/BasePage";
import ApplicationUrl from "../../helpers/applicationUrl";
import UnifyBasePage from "../../unify/pages/UnifyBasePage";
import UnifyLoginPage from "../../unify/pages/UnifyLoginPage";

test.describe("Login Test Feature", async () => {
  let basePage: BasePage;
  let unifyLoginPage: UnifyLoginPage;
  let mainPage: UnifyBasePage;

  test.beforeEach(async ({ page }) => {
    basePage = new BasePage(page);
    unifyLoginPage = new UnifyLoginPage(page);
    mainPage = new UnifyBasePage(page);
    await basePage.loadApplication(ApplicationUrl.UNIFY);
    await page.setViewportSize({ width: 1400, height: 900});
  });

  test.afterEach(async ({ context }) => {
    await context.clearCookies();
  });

  test("Login with wrong credentials", async () => {
    await unifyLoginPage.loginToUnify("sro", "2");
    await unifyLoginPage.validateHeaderMessage(
      "Incorrect User Name or Password."
    );
  });

  test("Login with correct credentials", async () => {
    await unifyLoginPage.loginToUnify("sro", "1");
    await mainPage.validateLogin();
    
  });
});

```
**Error:**

```javascript

PS D:\SroDev\sro4\uiAutomation\PlaywrightTest> npx playwright test
Using config at D:\SroDev\sro4\uiAutomation\PlaywrightTest\playwright.config.ts

Running 2 tests using 2 workers
Starting the run with 2 tests

Starting test Login with correct credentials
     tests\unify\loginTest.spec.ts:31:8 › Login Test Feature Login with correct credentials
Starting test Navigate between all categories
  ✓  tests\unify\loginTest.spec.ts:31:8 › Login Test Feature Login with correct credentials (13s)
     tests\unify\modulesNavigation.spec.ts:30:8 › Navigation Feature Navigate between all categories
  ✓  tests\unify\modulesNavigation.spec.ts:30:8 › Navigation Feature Navigate between all categories (26s)
Finished the run: passed

  Slow test: tests\unify\modulesNavigation.spec.ts (26s)

  2 passed (29s)
Error: ENOENT: no such file or directory, copyfile 'D:\SroDev\sro4\uiAutomation\PlaywrightTest\allure-results\0b8e8f62-d8c4-4cf6-80ce-6aee29539b0e-attachment.webm' -> 
'D:\SroDev\sro4\uiAutomation\PlaywrightTest\test-results\tests-unify-loginTest-Login-with-correct-credentials\5993eb7832ebade5cf638520f9855b04.webm'
    at copyFileSync (fs.js:1790:3)
    at FileSystemAllureWriter.writeAttachmentFromPath (D:\SroDev\sro4\uiAutomation\PlaywrightTest\node_modules\allure-js-commons\src\writers\FileSystemAllureWriter.ts:27:17)
    at AllureRuntime.writeAttachmentFromPath (D:\SroDev\sro4\uiAutomation\PlaywrightTest\node_modules\allure-js-commons\src\AllureRuntime.ts:55:17)
    at processSuite (D:\SroDev\sro4\uiAutomation\PlaywrightTest\node_modules\allure-playwright\src\index.ts:97:25)
    at processSuite (D:\SroDev\sro4\uiAutomation\PlaywrightTest\node_modules\allure-playwright\src\index.ts:122:9)
    at processSuite (D:\SroDev\sro4\uiAutomation\PlaywrightTest\node_modules\allure-playwright\src\index.ts:122:9)
    at processSuite (D:\SroDev\sro4\uiAutomation\PlaywrightTest\node_modules\allure-playwright\src\index.ts:122:9)
    at AllureReporter.onEnd (D:\SroDev\sro4\uiAutomation\PlaywrightTest\node_modules\allure-playwright\src\index.ts:126:5)
    at Multiplexer.onEnd (D:\SroDev\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\reporters\multiplexer.js:73:115)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Runner._run (D:\SroDev\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\runner.js:363:7) {
  errno: -4058,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: 'D:\\SroDev\\sro4\\uiAutomation\\PlaywrightTest\\allure-results\\0b8e8f62-d8c4-4cf6-80ce-6aee29539b0e-attachment.webm',
  dest: 'D:\\SroDev\\sro4\\uiAutomation\\PlaywrightTest\\test-results\\tests-unify-loginTest-Login-with-correct-credentials\\5993eb7832ebade5cf638520f9855b04.webm'    
}
PS D:\SroDev\sro4\uiAutomation\PlaywrightTest>

```
**Describe the bug**

The issue with allure-report behavior.
If I understand correctly - it tries to copy the **.webm** file from the allure-results folder, which contains only **.json** generated files to **test-results** folder that contains video, screenshot, and trace files.
I have an allure report in the configuration. If I run the test without an allure report - it works as well.

**Comment by AlexKomanov** [comment]
Also occurs in version 1.14.0

**Comment by AlexKomanov** [comment]
I did some checks:
Playwright: 1.13.1 + Allure-Playwright: 2.0.0-beta.11 -> works as well.
![image](https://user-images.githubusercontent.com/52656401/131668960-107a2fcd-eb07-4100-884c-6f5655a7fd12.png)


![image](https://user-images.githubusercontent.com/52656401/131668901-5daa13d7-c5ed-4a23-b4de-d5549e80a2cf.png)

**Comment by AlexKomanov** [comment]
### Playwright: 1.14.0 + Allure-Playwright: 2.0.0-beta.11 -> works as well.
![image](https://user-images.githubusercontent.com/52656401/131672004-04388ad7-e5ec-49c1-826b-bdee87bbbfb8.png)
![image](https://user-images.githubusercontent.com/52656401/131672086-af8913cd-5b78-400a-8fb0-d083782baf36.png)

### Playwright: 1.14.0 + Allure-Playwright: 2.0.0-beta.12 -> fails
![image](https://user-images.githubusercontent.com/52656401/131672397-7af0c45f-757b-4c3b-8a3f-258042510a15.png)
![image](https://user-images.githubusercontent.com/52656401/131672441-7f8b7197-cf64-46fc-a6da-92988f7bbb6f.png)

**Comment by AlexKomanov** [comment]
### Playwright: 1.14.1 + Allure-Playwright: 2.0.0-beta.11 -> works as well.
![image](https://user-images.githubusercontent.com/52656401/131673346-2094ad22-43b9-40c3-b4a7-43cf76289151.png)
![image](https://user-images.githubusercontent.com/52656401/131673470-ec627178-366c-41a1-a9c6-874c0afc505e.png)

### Playwright: 1.14.1 + Allure-Playwright: 2.0.0-beta.12 -> fails.
![image](https://user-images.githubusercontent.com/52656401/131673607-038d0667-dac2-4912-a9d4-27a3e3da8fb9.png)
![image](https://user-images.githubusercontent.com/52656401/131673684-51185e16-92e3-4425-a6e5-85a76dc7921c.png)

**Comment by AlexKomanov** [comment]
Another interesting issue.
In case I install the dependencies with allure-report via npm install command -> I'll get the error in the test, the same as mention above.

In case I add the allure-playwright in particular command (npm i allure-playwright@2.0.0-beta.11) - I pass the tests.

See the attached videos:

1. Adding all dependencies:


https://user-images.githubusercontent.com/52656401/131677587-a2f9a129-6d6e-4738-b73b-80e91036ee96.mp4

2. Adding dependencies without allure, and adding it in another particular step:


https://user-images.githubusercontent.com/52656401/131678351-f99b5cca-d917-4191-868d-0cb17bf68fc9.mp4


Until these cases - I thought it related to the allure version. But in this case - I don't understand how it occurs.

**Comment by Nav-2d** [comment]
I am guessing it is similar to this issue logged in `allure-js` repo: https://github.com/allure-framework/allure-js/issues/347

**Comment by AlexKomanov** [comment]
Looks like.
The biggest question - why we get different results depends on different ways of allure installation.

**Comment by yury-s** [comment]
Do you happen to use `video: on, preserveOutput: 'failures-only'` in your config? In that case recorded videos would be deleted if the tests passed and the reporter could get attachments pointing to the deleted video path. Throwing here is a reporter bug but I'd like to understand what triggers it today.

**Comment by AlexKomanov** [comment]
@yury-s 

I have no option as you mentioned:

![image](https://user-images.githubusercontent.com/52656401/131797505-21a04485-b2a9-4576-9c9b-e59c0e6c956a.png)

But I did something similar -> 'retain-on-failure':

![image](https://user-images.githubusercontent.com/52656401/131798424-3e90a7f4-986d-4c4d-a428-1abf156097c5.png)

It triggered the issue: **Error: Unrecognized extension: application/zip**

![image](https://user-images.githubusercontent.com/52656401/131798488-3409959c-c25d-4edc-9b91-ba830ca9f9ae.png)

And also, the 'off' mode of video -> triggers the same issue.:

![image](https://user-images.githubusercontent.com/52656401/131798671-c9836fed-82f4-40ad-a45a-d3569709fde6.png)

I checked with 2 versions: 
1. **2.0.0-beta.12**

![image](https://user-images.githubusercontent.com/52656401/131798984-fb526bc0-5774-4740-80eb-d69139e20c24.png)

2.  **2.0.0-beta.11**

![image](https://user-images.githubusercontent.com/52656401/131799854-dcbbd043-4e6a-4f53-8c36-e3476b72e71f.png)

The behavior is the same:
- In case the video with 'on' mode - it triggers the original issue of the bug.
- In the case of 'retain-on-failure' or 'off' modes - it triggers the mentioned above issue.

**Comment by yury-s** [comment]
> * In case the video with 'on' mode - it triggers the original issue of the bug.

That explains why the .webm file is not there. The exception should be fixed by the allure-js patch above.

> * In the case of 'retain-on-failure' or 'off' modes - it triggers the mentioned above issue.

Ok, this is another issue.

**Comment by yury-s** [comment]
Both problems should be fixed in 2.0.0-beta.13.

**Comment by sinhaman1909** [comment]
@yury-s 

I'm using 2.0.0-beta.16 and the problem is still isn't fixed. .webm file is still missing from the allure dashboard for me.

**Comment by VasanthVJ** [comment]
this issue still exists on stable versions. occurring randomly
